###
GET http://localhost:3000/

###
GET http://localhost:3000/api/items

###
GET http://localhost:3000/api/items/smart%20watch

###
POST http://localhost:3000/api/items
Content-Type: application/json

{
    "name": "Item 1",
    "style": "Item 1 description",
    "price": 100
}

###
DELETE http://localhost:3000/api/items/5